from PIL import Image, ImageFilter

# img = Image.open('images/pikachu.jpg')
img2 = Image.open('images/id.jpg')
#print(img2.size)
img2.thumbnail((400, 400))
img2.save("thumbnail.png", 'png')
print(img2.size)
#print(new_img.size)
#print(new_img.mode)
# filtered_img = img.filter(ImageFilter.BLUR)
# filtered_img = img.filter(ImageFilter.SMOOTH)
# filtered_img = img.filter(ImageFilter.SHARPEN)
# filtered_img = img.convert('L')

# print(img.format)
# print(img.size)
# print(img.mode)
# print(dir(img))
# filtered_img.save("blur.png", 'png')
# filtered_img.save("smooth.png", 'png')
# filtered_img.save("sharpen.png", 'png')
# crooked = filtered_img.rotate(180)
# filtered_img.save("grey.png", 'png')
# crooked.save("grey2.png", 'png')
# resize = filtered_img.resize((300, 300))
# box = (100, 100, 400, 400)
# region = filtered_img.crop(box)
# region.save("crop.png", 'png')
# resize.save("grey3.png", 'png')
# filtered_img.show()
# resize = img2.resize(640, 640)
#img2.show()
